services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - /backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      LIBRE_TRANSLATE_API_URL: http://translator:5000
    depends_on:
      - translator

  translator:
    image: libretranslate/libretranslate
    ports:
      - "5000:5000"
    tty: true
    restart: always